apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-backend
  labels:
    app: petstore-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petstore-backend
  template:
    metadata:
      labels:
        app: petstore-backend
    spec:
      containers:
      - name: backend
        image: cyacrtest.azurecr.io/backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: petstore-backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: petstore-backend
