apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-database
  labels:
    app: petstore-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore-database
  template:
    metadata:
      labels:
        app: petstore-database
    spec:
      containers:
      - name: database
        image: cyacrtest.azurecr.io/database:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: petstore-db-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: "petstore"
---
apiVersion: v1
kind: Service
metadata:
  name: petstore-database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: petstore-database
