apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-db
  labels:
    app: petstore-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore-db
  template:
    metadata:
      labels:
        app: petstore-db
    spec:
      containers:
        - name: database
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: petstore
            - name: POSTGRES_USER
              value: petuser
            - name: POSTGRES_PASSWORD
              value: petpassword
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: petstore-db
spec:
  type: ClusterIP
  selector:
    app: petstore-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
