apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-frontend
  labels:
    app: petstore-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petstore-frontend
  template:
    metadata:
      labels:
        app: petstore-frontend
    spec:
      containers:
        - name: frontend
          image: cyacrtest/petstore-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: petstore-frontend
spec:
  type: LoadBalancer
  selector:
    app: petstore-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
