name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: cyacrtest.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push frontend image
      run: |
        docker build -t cyacrtest.azurecr.io/frontend:latest ./frontend
        docker push cyacrtest.azurecr.io/frontend:latest

    - name: Build and Push backend image
      run: |
        docker build -t cyacrtest.azurecr.io/backend:latest ./backend
        docker push cyacrtest.azurecr.io/backend:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes cluster
      run: |
          kubectl apply -f manifests/
